# Generated by Django 5.0.2 on 2024-02-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=100)),
                ('specific_focus_ares', models.CharField(max_length=50)),
                ('lawyer_resume', models.CharField(max_length=100)),
                ('lawyer_bio', models.TextField()),
                ('password_hash', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Lawyer',
                'verbose_name_plural': 'Lawyers',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('lawyer_id', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('practice_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('practice_area_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Lawyer_practice_areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication_service.lawyer')),
                ('practice_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication_service.roles')),
            ],
            options={
                'verbose_name': 'Lawyer Practice Area',
                'verbose_name_plural': 'Lawyer Practice Areas',
            },
        ),
    ]
